language: r
r: bioc-release
cache: packages
sudo: false
matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - g++-6
          sources:
            - ubuntu-toolchain-r-test
      env:
        - MATRIX_EVAL="CXX=g++-6 && CC=gcc-6"


before_install:
  - eval "${MATRIX_EVAL}"
  - bash configure.sh
  - gcc --version
  - g++ --version

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'