language: r
r: bioc-release
matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - g++-6
          sources:
            - ubuntu-toolchain-r-test
      env:
        - MATRIX_EVAL="CXX=g++-6 && CC=gcc-6"


before_install:
  - eval "${MATRIX_EVAL}"
  - bash configure.sh
  - cat DESCRIPTION
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  - gcc --version
  - g++ --version

install:

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'